from rest_framework import serializers
from ..models import Recipe, Category, Ingredient, RecipeIngredient, RecipeInstruction

# --- 1. Base Serializers for Category and Ingredient (simple CRUD) ---

class CategorySerializer(serializers.ModelSerializer):
    class Meta:
        model = Category
        fields = ['id', 'name']
        read_only_fields = ['id'] # ID is generated by DB

class IngredientSerializer(serializers.ModelSerializer):
    class Meta:
        model = Ingredient
        fields = ['id', 'name']
        read_only_fields = ['id'] # ID is generated by DB

# --- 2. Serializer for RecipeIngredient (nested, for display AND write within Recipe) ---

class RecipeIngredientSerializer(serializers.ModelSerializer):
    name = serializers.CharField(source='ingredient.name', read_only=True)

    ingredient = serializers.PrimaryKeyRelatedField(queryset=Ingredient.objects.all())

    class Meta:
        model = RecipeIngredient
        fields = ['id', 'name', 'quantity', 'unit', 'ingredient']
        read_only_fields = ['id', 'name']

class RecipeInstructionSerializer(serializers.ModelSerializer):
    class Meta:
        model = RecipeInstruction
        fields = ['id', 'text', 'order']

# --- 3. Main Recipe Serializers ---

# Serializer for Reading/Displaying Recipes (GET requests)
class RecipeSerializer(serializers.ModelSerializer):
    category = CategorySerializer(read_only=True)
    recipe_ingredients = serializers.SerializerMethodField(method_name='get_recipe_ingredients')
    recipe_instructions = serializers.SerializerMethodField(method_name='get_recipe_instructions')
    owner = serializers.CharField(source='owner.username', read_only=True, default=None)

    def get_recipe_ingredients(self, obj):
        return RecipeIngredientSerializer(obj.recipeingredient_set.all(), many=True).data
    
    def get_recipe_instructions(self, obj):
        return RecipeInstructionSerializer(obj.recipeinstruction_set.all(), many=True).data

    class Meta:
        model = Recipe
        fields = [
            'id', 'title', 'description', 'recipe_instructions', 
            'prep_time', 'cook_time', 'servings',
            'category', 'recipe_ingredients',
            'owner', 'is_public',
            'created_at', 'updated_at'
        ]
        read_only_fields = ['id', 'owner', 'created_at']

# Serializer for Creating and Updating Recipes (POST, PUT, PATCH requests)
class RecipeWriteSerializer(serializers.ModelSerializer):
    # Expect Category ID for input (PrimaryKeyRelatedField)
    category = serializers.PrimaryKeyRelatedField(queryset=Category.objects.all(), allow_null=True) # allow_null if category can be null in model

    # Expect a list of RecipeIngredient data for input
    # This expects a list of dictionaries like [{"ingredient": 1, "quantity": 200, "unit": "g"}]
    recipe_ingredients = RecipeIngredientSerializer(many=True, required=False)
    recipe_instructions = RecipeInstructionSerializer(many=True, required=True)


    class Meta:
        model = Recipe
        fields = [
            'id', 'title', 'description', 'recipe_instructions',
            'prep_time', 'cook_time', 'servings',
            'category', 'recipe_ingredients', 'is_public',
        ]

    def create(self, validated_data):
        # Pop the nested data first
        recipe_ingredients_data = validated_data.pop('recipe_ingredients', [])
        recipe_instructions_data = validated_data.pop('recipe_instructions', [])
        
        # Create the Recipe instance
        recipe = Recipe.objects.create(**validated_data)

        # Create RecipeIngredient instances
        for ingredient_data in recipe_ingredients_data:
            RecipeIngredient.objects.create(recipe=recipe, **ingredient_data)

        for instruction_data in recipe_instructions_data:
            RecipeInstruction.objects.create(recipe=recipe, **instruction_data)

        return recipe

    def update(self, instance, validated_data):
        # Pop the nested data first
        recipe_ingredients_data = validated_data.pop('recipe_ingredients', None)
        recipe_instructions_data = validated_data.pop('recipe_instructions', None)

        # Update main Recipe fields using the parent's update method
        instance = super().update(instance, validated_data)

        # Handle nested RecipeIngredient updates
        if recipe_ingredients_data is not None:
            instance.recipeingredient_set.all().delete()
            for ingredient_data in recipe_ingredients_data:
                RecipeIngredient.objects.create(recipe=instance, **ingredient_data)

        if recipe_instructions_data is not None:
            instance.recipeinstruction_set.all().delete()
            for instruction_data in recipe_instructions_data:
                # Ignore client-supplied pk so rows are always recreated after delete
                instruction_data = {
                    k: v for k, v in instruction_data.items() if k != "id"
                }
                RecipeInstruction.objects.create(recipe=instance, **instruction_data)

        return instance