# Generated by Django 6.0.4 on 2026-04-09 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_migrate_categories_and_images_to_tags_and_recipe_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
