# Generated by Django 5.1.7 on 2026-04-09 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_heart_collection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Heart',
            new_name='Like',
        ),
        migrations.AlterField(
            model_name='like',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='likes',
                to='recipes.recipe',
            ),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='likes',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
